### ISSUE TITLE
Make tan equally opinionated about tabs?

### ISSUE THREAD

**Issue by joezeng** [jleclanche/tan#6]
The only difference between this project and Black seems to be that it allows the use of tabs instead of the more popular 4-spaces standard for indentation. If running `tan` without the `--use-tabs` option on is functionally equivalent to just running `black`, why not just make this variation of the formatter always output tabs, without the option to disable it? For people who don't like tabs and want to stick with spaces, `black` already does what they want, and they should just use that.

Not really a feature request but rather a "removal of a feature" request, but it's something to consider.

**Comment by jleclanche** [comment]
I won't do this for three reasons:

- I don't intend to maintain tan any more than the --use-tabs option
- I want to be fully backwards-compatible with black (because then you don't need to have tan for some projects and black for some others)
- This is supposed to be mergeable into Black, if Łukasz ever stops being so stubborn.
